version: "3"
services:
  hmpps-jobs-board-integration-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-jobs-board-integration-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
      - SPRING_PROFILES_ACTIVE=dev,local
      - API_BASE_URL_JOBSBOARD=https://jobs-board-api-dev.hmpps.service.justice.gov.uk
      - API_BASE_URL_MNJOBBOARD=https://testservices.sequation.net/sequation-job-api
      - MN_AUTH_URL=https://testservices.sequation.net/sequation-authentication-api
      - MN_AUTH_USERNAME=<OVERRIDE_THIS>
      - MN_AUTH_PASSWORD=<OVERRIDE_THIS>
      - MN_AUTH_APP_ID=<OVERRIDE_THIS>
      - API_CLIENT_ID=<OVERRIDE_THIS>
      - API_CLIENT_SECRET=<OVERRIDE_THIS>

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: integration-hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

  job-board-intg-db:
    image: postgres:16.3
    container_name: integration-db
    networks:
      - hmpps
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=job-board-intg
      - POSTGRES_USER=job-board-intg
      - POSTGRES_DB=job-board-intg

  localstack:
    image: localstack/localstack:4
    container_name: integration-localstack
    ports:
      - "4566:4566"             # LocalStack Gateway
      - "4510-4559:4510-4559"   # external services port range
    environment:
      - SERVICES=sqs
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
