hmpps-auth:
  url: "http://localhost:8090/auth"

# example client configuration for calling out to other services
# TODO: Remove / replace this configuration
example-api:
  url: "http://localhost:8080"
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"

api:
  base.url:
    jobsboard: "https://jobs-board-api-dev.hmpps.service.justice.gov.uk"
    mnjobboard: "https://testservices.sequation.net/sequation-job-api"
  integration:
    enabled: false
  client.logging:
    enabled: false

spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/job-board-intg'
    username: 'job-board-intg'
    password: 'job-board-intg'
  flyway:
    user: 'job-board-intg'
    password: 'job-board-intg'

logging.level:
  uk.gov.justice.digital.hmpps.jobsboardintegrationapi:
    shared.infrastructure: DEBUG
  reactor.netty.http.client: INFO