api.integration:
  enabled: true

hmpps.sqs:
  provider: localstack
  queues:
    integrationqueue:
      queueName: hmpps_jobs_board_integration_queue
      dlqName: hmpps_jobs_board_integration_dlq
      dlqMaxReceiveCount: 1
