server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  jpa:
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=disable&autosave=conservative'
  flyway:
    baseline-on-migrate: true
    clean-disabled: false
  security:
    oauth2:
      client:
        provider:
          mn-auth:
            token-uri: ${mn-auth.url}/systemlogin

        registration:
          mn-job-board-api:
            provider: mn-auth
            client-id: ${mn-auth.username}
            client-secret: ${mn-auth.password}
            authorization-grant-type: client_credentials
            scope: read,write


hmpps-auth:
  url: "http://localhost:8090/auth"

hmpps.sqs:
  provider: localstack
  queues:
    integrationqueue:
      queueName: hmpps_jobs_board_integration_queue
      dlqName: hmpps_jobs_board_integration_dlq

api:
  base.url:
    jobsboard: "http://localhost:8092"
    mnjobboard: "http://localhost:8093"
  client:
    id: "api-client"
    secret: "api-client-secret"

  integration:
    enabled: true

mn-auth:
  url: "http://localhost:8091/mn-auth"
  username: "mn_user"
  password: "mn_password"
  app-id: 1

logging:
  level:
    uk.gov.justice.digital.hmpps.jobsboardintegrationapi.shared.infrastructure: DEBUG
