server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  jpa:
    show-sql: true
  datasource:
    url: 'jdbc:postgresql://${DATABASE_ENDPOINT}/${DATABASE_NAME}?sslmode=disable&autosave=conservative'
  flyway:
    baseline-on-migrate: true
    clean-disabled: false

hmpps-auth:
  url: "http://localhost:8090/auth"

hmpps.sqs:
  provider: localstack
  queues:
    integrationqueue:
      queueName: hmpps_jobs_board_integration_queue

api:
  base.url:
    jobsboard: "http://localhost:8092"
    mnjobboard: "http://localhost:8093"
  client:
    id: "api-client"
    secret: "api-client-secret"

  integration:
    enabled: true

mn.jobboard:
  api.token: "mn-api-bearer-token"

logging:
  level:
    uk.gov.justice.digital.hmpps.jobsboardintegrationapi.shared.infrastructure: TRACE
