server:
  shutdown: immediate

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

hmpps-auth:
  url: "http://localhost:8090/auth"

# example client configuration for calling out to other services
# TODO: Remove / replace this configuration
example-api:
  url: "http://localhost:8091"
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"

hmpps.sqs:
  provider: localstack
  queues:
    integrationqueue:
      queueName: hmpps_jobs_board_integration_queue

api:
  base.url:
    jobsboard: "http://localhost:8092"
  client:
    id: "api-client"
    secret: "api-client-secret"

  integration:
    enabled: true