generic-service:
  nameOverride: hmpps-jobs-board-integration-api
  productId: "DPS015" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-jobs-board-integration-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-jobs-board-integration-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }
        location /integration-admin/resend-employers {
          deny all;
          return 401;
        }
        location /integration-admin/resend-jobs {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    API_INTEGRATION_ENABLED: false

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-jobs-board-integration-api:
      API_CLIENT_ID: "SYSTEM_CLIENT_ID"
      API_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      MN_JOBBOARD_API_TOKEN: "MN_JOBBOARD_API_TOKEN"
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    sqs-integration-queue-instance-output:
      HMPPS_SQS_QUEUES_INTEGRATIONQUEUE_QUEUE_NAME: "sqs_queue_name"
    sqs-integration-dlq-instance-output:
      HMPPS_SQS_QUEUES_INTEGRATIONQUEUE_DLQ_NAME: "sqs_queue_name"

  allowlist:
    groups:
      - internal

  retryDlqCronjob:
    enabled: true

generic-prometheus-alerts:
  targetApplication: hmpps-jobs-board-integration-api
