---
# Per environment values which override defaults in hmpps-jobs-board-integration-api/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: jobs-board-integration-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    # Template kotlin calls out to itself to provide an example of a service call
    # TODO: This should be replaced by a call to a different service, or removed
    EXAMPLE_API_URL: "https://jobs-board-integration-api-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_JOBSBOARD: "https://jobs-board-api-preprod.hmpps.service.justice.gov.uk"
    API_BASE_URL_MNJOBBOARD: "https://preprodservices.sequation.net/sequation-job-api"   # URL to be confirmed

  serviceAccountName: education-skills-work-employment-preprod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: education-alerts-non-prod
